version: "3.9"
services:
  openvscode-nginx:
    image: ghcr.io/hudsonm62/nginx-vscode-docker:main # never use `latest`
    container_name: vscode-server
    restart: unless-stopped
    volumes:
      - vscode-config:/config
      - path/to/cert.crt:/etc/nginx/certs/localhost.crt:ro     # cert file name defined in nginx.default.conf
      - path/to/private.key:/etc/nginx/certs/localhost.key:ro  # cert file name defined in nginx.default.conf
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro # provide your own or update and mount the default one
    ports:
      - "443:443"   # Proxied-HTTPS
      - "80:8080"   # Proxied-HTTP
    # - "3000:3000" # Direct to VS Code
    networks:
      - vscode-dnet

volumes:
  vscode-config:
networks:
  vscode-dnet: